using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OoT.API
{

    public enum InventoryItem
    {
        DEKU_STICKS,
        DEKU_NUTS,
        BOMBS,
        FAIRY_BOW,
        FIRE_ARROWS,
        DINS_FIRE,
        FAIRY_SLINGSHOT,
        FAIRY_OCARINA,
        OCARINA_OF_TIME,
        BOMBCHUS,
        HOOKSHOT,
        LONGSHOT,
        ICE_ARROWS,
        FARORES_WIND,
        BOOMERANG,
        LENS_OF_TRUTH,
        MAGIC_BEANS,
        MEGATON_HAMMER,
        LIGHT_ARROWS,
        NAYRUS_LOVE,
        EMPTY_BOTTLE,
        RED_POTION,
        GREEN_POTION,
        BLUE_POTION,
        BOTTLED_FAIRY,
        BOTTLED_FISH,
        LON_LON_MILK,
        RUTOS_LETTER,
        BLUE_FIRE,
        BOTTLED_BUGS,
        BOTTLED_BIG_POE,
        LON_LON_MILK_HALF,
        BOTTLED_POE,
        WEIRD_EGG,
        CHILD_CUCCO,
        ZELDAS_LETTER,
        KEATON_MASK,
        SKULL_MASK,
        SPOOKY_MASK,
        BUNNY_HOOD,
        GORON_MASK,
        ZORA_MASK,
        GERUDO_MASK,
        MASK_OF_TRUTH,
        SOLD_OUT,
        POCKET_EGG,
        POCKET_CUCCO,
        COJIRO,
        ODD_MUSHROOM,
        ODD_POTION,
        POACHERS_SAW,
        BROKEN_GORON_SWORD,
        PRESCRIPTION,
        EYEBALL_FROG,
        EYE_DROPS,
        CLAIM_CHECK,
        BOW_FIRE_ARROWS,
        BOW_ICE_ARROWS,
        BOW_LIGHT_ARROWS,
        NONE = 0xff,
    }

    public enum InventorySlot
    {
        DEKU_STICKS = 0,
        DEKU_NUTS,
        BOMBS,
        FAIRY_BOW,
        FIRE_ARROWS,
        DINS_FIRE,
        FAIRY_SLINGSHOT,
        OCARINA,
        BOMBCHUS,
        HOOKSHOT,
        ICE_ARROWS,
        FARORES_WIND,
        BOOMERANG,
        LENS_OF_TRUTH,
        MAGIC_BEANS,
        MEGATON_HAMMER,
        LIGHT_ARROWS,
        NAYRUS_LOVE,
        BOTTLE1,
        BOTTLE2,
        BOTTLE3,
        BOTTLE4,
        ADULT_TRADE_ITEM,
        CHILD_TRADE_ITEM,
        COUNT
    }

}
