//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoT.API {
    
    
    public enum LinkAge {
        
        LINK_AGE_ADULT,
        
        LINK_AGE_CHILD,
    }
}
