//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoT.API {
    
    
    public enum MagicChangeType {
        
        // Consume Magic immediately without preview
        MAGIC_CONSUME_NOW,
        
        // Sets consume target but waits to consume. No yellow magic preview to target consumption. Unused
        MAGIC_CONSUME_WAIT_NO_PREVIEW,
        
        // Identical behaviour to MAGIC_CONSUME_NOW. Unused
        MAGIC_CONSUME_NOW_ALT,
        
        // Lens consumption
        MAGIC_CONSUME_LENS,
        
        // Sets consume target but waits to consume. Draws yellow magic to target consumption
        MAGIC_CONSUME_WAIT_PREVIEW,
        
        // Sets a target to add magic
        MAGIC_ADD,
    }
}
