//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoT.API {
    
    
    public enum SubTimerState {
        
        SUBTIMER_STATE_OFF,
        
        // Init timer that counts down
        SUBTIMER_STATE_DOWN_INIT,
        
        // Display initial time keep it fixed at the screen center
        SUBTIMER_STATE_DOWN_PREVIEW,
        
        // Move to top-left corner
        SUBTIMER_STATE_DOWN_MOVE,
        
        // Counting down
        SUBTIMER_STATE_DOWN_TICK,
        
        // Time is up trigger a transition reset button items spoil trade quest items
        SUBTIMER_STATE_RESPAWN,
        
        // Time is up stop counting
        SUBTIMER_STATE_STOP,
        
        // Init timer that counts up
        SUBTIMER_STATE_UP_INIT,
        
        // Display initial time keep it fixed at the screen center
        SUBTIMER_STATE_UP_PREVIEW,
        
        // Move to top-left corner
        SUBTIMER_STATE_UP_MOVE,
        
        // Counting up
        SUBTIMER_STATE_UP_TICK,
    }
}
