//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoT.API {
    
    
    public enum SunsSongState {
        
        SUNSSONG_INACTIVE,
        
        // the suns ocarina effect signals that the song has finished playing
        SUNSSONG_START,
        
        // suns was played where time passes speed up the advancement of time
        SUNSSONG_SPEED_TIME,
        
        // time does not advance but signals the song was played. used for freezing redeads
        SUNSSONG_SPECIAL,
    }
}
