//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoT.API {
    
    
    public enum ChamberCutsceneNum {
        
        CHAMBER_CS_FOREST,
        
        CHAMBER_CS_FIRE,
        
        CHAMBER_CS_WATER,
        
        CHAMBER_CS_SPIRIT,
        
        CHAMBER_CS_SHADOW,
        
        CHAMBER_CS_LIGHT,
    }
}
