//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoT.API {
    
    
    public enum HudVisibilityMode {
        
        HUD_VISIBILITY_NO_CHANGE,
        
        HUD_VISIBILITY_NOTHING,
        
        // Identical to HUD_VISIBILITY_NOTHING
        HUD_VISIBILITY_NOTHING_ALT,
        
        // See above
        HUD_VISIBILITY_HEARTS_FORCE,
        
        HUD_VISIBILITY_A,
        
        // See above
        HUD_VISIBILITY_A_HEARTS_MAGIC_FORCE,
        
        // See above
        HUD_VISIBILITY_A_HEARTS_MAGIC_MINIMAP_FORCE,
        
        // Only raises button alphas if not disabled
        HUD_VISIBILITY_ALL_NO_MINIMAP_BY_BTN_STATUS,
        
        HUD_VISIBILITY_B,
        
        HUD_VISIBILITY_HEARTS_MAGIC,
        
        // Identical to HUD_VISIBILITY_B
        HUD_VISIBILITY_B_ALT,
        
        HUD_VISIBILITY_HEARTS,
        
        HUD_VISIBILITY_A_B_MINIMAP,
        
        // See above
        HUD_VISIBILITY_HEARTS_MAGIC_FORCE,
        
        // Only raises button alphas if not disabled
        HUD_VISIBILITY_ALL = 50,
        
        HUD_VISIBILITY_NOTHING_INSTANT,
    }
}
