//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoT.API {
    
    
    public enum Language {
        
        LANGUAGE_ENG,
        
        LANGUAGE_GER,
        
        LANGUAGE_FRA,
        
        LANGUAGE_MAX,
    }
}
