//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoT.API {
    
    
    public enum MagicState {
        
        // Regular gameplay
        MAGIC_STATE_IDLE,
        
        // Sets the speed at which magic border flashes
        MAGIC_STATE_CONSUME_SETUP,
        
        // Consume magic until target is reached or no more magic is available
        MAGIC_STATE_CONSUME,
        
        // Flashes border and freezes Dark Link
        MAGIC_STATE_METER_FLASH_1,
        
        // Flashes border and draws yellow magic to preview target consumption
        MAGIC_STATE_METER_FLASH_2,
        
        // Reset colors and return to idle
        MAGIC_STATE_RESET,
        
        // Flashes border with no additional behaviour
        MAGIC_STATE_METER_FLASH_3,
        
        // Magic slowly consumed by lens.
        MAGIC_STATE_CONSUME_LENS,
        
        // Step `magicCapacity` to full capacity
        MAGIC_STATE_STEP_CAPACITY,
        
        // Add magic until magicFillTarget is reached.
        MAGIC_STATE_FILL,
        
        // Add requested magic
        MAGIC_STATE_ADD,
    }
}
