//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoT.API {
    
    
    public enum RespawnMode {
        
        RESPAWN_MODE_DOWN,
        
        RESPAWN_MODE_RETURN,
        
        RESPAWN_MODE_TOP,
        
        RESPAWN_MODE_MAX,
    }
}
