//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModLoader.OoT.API {
    
    
    public class WrapperRespawnData {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public WrapperVec3f pos {get => this._pos(); set => this._pos(value);}//;
        
        public s16 yaw {get => this._yaw(); set => this._yaw(value);}//;
        
        public s16 playerParams {get => this._playerParams(); set => this._playerParams(value);}//;
        
        public s16 entranceIndex {get => this._entranceIndex(); set => this._entranceIndex(value);}//;
        
        public u8 roomIndex {get => this._roomIndex(); set => this._roomIndex(value);}//;
        
        public s8 data {get => this._data(); set => this._data(value);}//;
        
        public u32 tempSwchFlags {get => this._tempSwchFlags(); set => this._tempSwchFlags(value);}//;
        
        public u32 tempCollectFlags {get => this._tempCollectFlags(); set => this._tempCollectFlags(value);}//;
        
        public WrapperRespawnData(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x1C;
        }
        
        private WrapperVec3f _pos() {
            return new WrapperVec3f(this.pointer + 0x00);
        }
        
        private void _pos(WrapperVec3f value) {
        }
        
        private s16 _yaw() {
            return Memory.RAM.ReadS16(this.pointer + 0x0C);
        }
        
        private void _yaw(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x0C, value);
        }
        
        private s16 _playerParams() {
            return Memory.RAM.ReadS16(this.pointer + 0x0E);
        }
        
        private void _playerParams(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x0E, value);
        }
        
        private s16 _entranceIndex() {
            return Memory.RAM.ReadS16(this.pointer + 0x10);
        }
        
        private void _entranceIndex(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x10, value);
        }
        
        private u8 _roomIndex() {
            return Memory.RAM.ReadU8(this.pointer + 0x12);
        }
        
        private void _roomIndex(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x12, value);
        }
        
        private s8 _data() {
            return Memory.RAM.ReadS8(this.pointer + 0x13);
        }
        
        private void _data(s8 value) {
            Memory.RAM.WriteS8(this.pointer + 0x13, value);
        }
        
        private u32 _tempSwchFlags() {
            return Memory.RAM.ReadU32(this.pointer + 0x14);
        }
        
        private void _tempSwchFlags(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x14, value);
        }
        
        private u32 _tempCollectFlags() {
            return Memory.RAM.ReadU32(this.pointer + 0x18);
        }
        
        private void _tempCollectFlags(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x18, value);
        }
    }
}
