//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModLoader.OoT.API {
    
    
    public enum EventInfHorsesState {
        
        EVENTINF_HORSES_STATE_0,
        
        EVENTINF_HORSES_STATE_1,
        
        EVENTINF_HORSES_STATE_2,
        
        EVENTINF_HORSES_STATE_3,
        
        EVENTINF_HORSES_STATE_4,
        
        EVENTINF_HORSES_STATE_5,
        
        EVENTINF_HORSES_STATE_6,
        
        EVENTINF_HORSES_STATE_7,
    }
}
