//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModLoader.OoT.API {
    
    
    public enum GameMode {
        
        GAMEMODE_NORMAL,
        
        GAMEMODE_TITLE_SCREEN,
        
        // Note: only instance type transitions swap to file select
        GAMEMODE_FILE_SELECT,
        
        GAMEMODE_END_CREDITS,
    }
}
