//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModLoader.OoT.API {
    
    
    public enum HighScores {
        
        // horseback archery
        HS_HBA,
        
        HS_POE_POINTS,
        
        HS_FISHING,
        
        HS_HORSE_RACE,
        
        HS_MARATHON,
        
        HS_UNK_05,
        
        HS_DAMPE_RACE,
    }
}
