//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModLoader.OoT.API {
    
    
    public enum SceneLayer {
        
        SCENE_LAYER_CHILD_DAY,
        
        SCENE_LAYER_CHILD_NIGHT,
        
        SCENE_LAYER_ADULT_DAY,
        
        SCENE_LAYER_ADULT_NIGHT,
        
        SCENE_LAYER_CUTSCENE_FIRST,
    }
}
