//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModLoader.OoT.API {
    
    
    public enum TimerState {
        
        TIMER_STATE_OFF,
        
        // Init env timer that counts down total time based on health resets on void-out kills at 0
        TIMER_STATE_ENV_HAZARD_INIT,
        
        // Display initial time keep it fixed at the screen center
        TIMER_STATE_ENV_HAZARD_PREVIEW,
        
        // Move to top-left corner
        TIMER_STATE_ENV_HAZARD_MOVE,
        
        // Counting down
        TIMER_STATE_ENV_HAZARD_TICK,
        
        // Init timer that counts down
        TIMER_STATE_DOWN_INIT,
        
        // Display initial time keep it fixed at the screen center
        TIMER_STATE_DOWN_PREVIEW,
        
        // Move to top-left corner
        TIMER_STATE_DOWN_MOVE,
        
        // Counting down
        TIMER_STATE_DOWN_TICK,
        
        TIMER_STATE_STOP,
        
        // Init timer that counts up
        TIMER_STATE_UP_INIT,
        
        // Display initial time keep it fixed at the screen center
        TIMER_STATE_UP_PREVIEW,
        
        // Move to top-left corner
        TIMER_STATE_UP_MOVE,
        
        // Counting up
        TIMER_STATE_UP_TICK,
        
        // Stop counting the timer
        TIMER_STATE_UP_FREEZE,
    }
}
