//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModLoader.OoT.API {
    
    
    public enum TimerId {
        
        // Takes priority in both counting and drawing. See `timerState` and `timerSeconds`
        TIMER_ID_MAIN,
        
        // See `subTimerState` and `subTimerSeconds`
        TIMER_ID_SUB,
        
        TIMER_ID_MAX,
    }
}
